#Targetname : Dependent target name
#<TAB>command

Build:
	gcc main.c -o add.out -lm

Run:
	./add.out
#Targetname : Dependent target name
#<TAB>command

Input:
	gcc main.c -o add.out -lm
Output:
	./add.out
